apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-list
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travel-list
  template:
    metadata:
      labels:
        app: travel-list
    spec:
      containers:
      - name: travel-list
        image: taninitash/travel-list:latest
        ports:
        - containerPort: 80
