name: React CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and Push Docker Image
      run: |
        docker build -t your-dockerhub-username/react-app .
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker tag react-app your-dockerhub-username/react-app:latest
        docker push your-dockerhub-username/react-app:latest

    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v3
      with:
        manifests: |
          ./k8s/react-deployment.yaml
          ./k8s/react-service.yaml
